### PR TITLE
Fixes and enhancements from mupen64plus-ae

### PR DESCRIPTION
**Pull request by littleguy77**
@Gillou68310 
Please let me know if I have misattributed anything or my explanations are not clear. Thanks :)

### CODE REVIEW

**Comment by richard42** [comment]
You could change the pixel array to 2048*2048*2 instead of *4, since you are reading bytes, and each pixel is 4 bytes, or 2 shorts.

**Comment by Gillou68310** [comment]
That's definitely the best solution ;-)
Just for information glReadPixels is storing in contiguous memory when using GL_RGBA that's why we can do that.

**Comment by littleguy77** [comment]
Thanks for the quick feedback.  I'll make the recommended changes, add some documentation in the comments, and reopen the pull request when it's ready.

**Comment by littleguy77** [comment]
Thanks for the suggestions.  Made the fixes and reopened the PR.

**Comment by richard42** [comment]
I would recommend removing the logging change, since it causes a performance issue.

**Comment by littleguy77** [comment]
The change actually improves performance, but I can remove it if you wish.

**Comment by littleguy77** [comment]
Ok, I removed the last commit.

**Comment by littleguy77** [comment]
@richard42  Just occurred to me I might have misread your last comment.  Which commit did you want me to remove?

https://github.com/littleguy77/mupen64plus-video-glide64mk2/commit/90601dbb94d501c6c84a9ab355fa244b1ebb1c29

https://github.com/littleguy77/mupen64plus-video-glide64mk2/commit/68fd85740119821b14795ad9ec012dd811cb035d

**Pull request merged**
